# Default values for the CANFAR Science Platform Helm Chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Hostname to use for all ingress routes (if not set, each service will use its own hostname setting)
  hostname: ""

  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  # Set the Registry URL pointing to the desired registry containing IVOA compliant services to lookup.
  # Example:
  #   registryURL: https://example.org/reg
  registryURL: ""

  # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
  # Example:
  #   oidcURI: https://iam.example.org
  oidcURI:

  # ID (URI) of the GMS Service.
  # Example:
  #   gmsID: ivo://example.org/gms
  gmsID:

  # Array of groups allowed to set the logging level.  If none set, then nobody can change the log level.
  # Example:
  #   loggingGroups:
  #     - "admin"
  #     - "/roles/prod/ops"
  loggingGroups: []

  # The IdentityManager class handling authentication.  This should generally be left alone unless deployed internally for the CADC.  Required.
  # Example:
  #   identityManagerClass: "org.opencadc.auth.StandardIdentityManager"
  identityManagerClass: "org.opencadc.auth.StandardIdentityManager"

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # The IdentityManager class handling authentication.  This should generally be left alone unless deployed internally for the CADC.  Required.
  # Example:
  #   identityManagerClass: "org.opencadc.auth.StandardIdentityManager"
  identityManagerClass: "org.opencadc.auth.StandardIdentityManager"

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  nodeSelector: {}

  tolerations: []

  affinity: {}

#
# Services that make up the CANFAR Science Platform
#
# Configuration for the Cavern service
cavern:
  enabled: true

# Configuration for the POSIX Mapper service
posix-mapper:
  enabled: true

# Configuration for the Skaha service
skaha:
  enabled: true

# Configuration for the Science Portal service
science-portal:
  enabled: true

# Configuration for the Storage UI service
storage-ui:
  enabled: true
