apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: "${skaha.jobname}"
    uid: "${skaha.jobuid}"
  name: skaha-desktop-svc-${skaha.sessionid}
  labels:
    run: skaha-desktop-svc-${skaha.sessionid}
spec:
  ports:
  - port: 6901
    protocol: TCP
    name: http-connection
  selector:
    canfar-net-sessionID: ${skaha.sessionid}
    canfar-net-sessionType: desktop
