version: 2

updates:
  - package-ecosystem: "helm"
    directories:
      - "helm/applications/skaha"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "helm"
