{{- if eq .Values.kueue.install true }}
---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: {{ .Release.Name }}-default
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: {{ .Release.Name }}-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ {{ .Values.skahaWorkload.namespace }} ]
  queueingStrategy: BestEffortFIFO
  cohort: {{ .Release.Name }}-cohort
  resourceGroups:
    - coveredResources:
{{- range $key := .Values.kueue.clusterQueueResources }}
      - {{ $key.name }}
{{- end }}
      flavors:
        - name: "{{ .Release.Name }}-default"
          resources:
{{ .Values.kueue.clusterQueueResources | toYaml | indent 10 }}
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
{{- end }}