---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
    cadc-log.properties: |
{{- range $val := .Values.loggingGroups }}
        group = {{ $val }}
{{- end }}
    cadc-registry.properties: |
        ivo://ivoa.net/std/GMS#search-1.0 = {{ .Values.gmsID | required "The GMS locator (gmsID) is required" }}
        ivo://ivoa.net/std/GMS#users-1.0 = {{ .Values.gmsID }}
        ivo://ivoa.net/std/UMS#users-1.0 = {{ .Values.gmsID }}
        ivo://ivoa.net/sso#OAuth = {{ .Values.oidcURI }}
        ivo://ivoa.net/sso#OpenID = {{ .Values.oidcURI }}

        # Ignore this, it's only here to satisfy the availability check.
        ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://cadc.nrc.ca/cred

        http://www.opencadc.org/std/posix#group-mapping-0.1 = {{ .Values.posixMapperResourceID | required "The locator for the POSIX Mapper service (posixMapperResourceID) is required" }}
        http://www.opencadc.org/std/posix#user-mapping-0.1 = {{ .Values.posixMapperResourceID }}

        ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ .Values.registryURL | required "A registryURL is required" }}

    catalina.properties: |
        tomcat.connector.scheme=https
        tomcat.connector.proxyName={{ .Values.hostname }}
        tomcat.connector.proxyPort=443
        ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
        ca.nrc.cadc.util.Log4jInit.messageOnly=true
        ca.nrc.cadc.auth.IdentityManager={{ .Values.identityManagerClass }}
        org.opencadc.skaha.posixCache.url=redis://{{ $.Release.Name }}-redis-master:6379

    war-rename.conf: |
        {{- if .Values.applicationName }}
        mv skaha.war {{ .Values.applicationName }}.war
        {{- end }}
