---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: skaha-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ skaha-workload, canfar-b-workload ]
  queueingStrategy: BestEffortFIFO
  cohort: skaha-cohort
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage"]
      flavors:
        - name: "default"
          # Cluster Hardware Configuration
          # Does not include
          #   - skaha.opencadc.org/node-type=service-node (p-nodes)
          #   - node-role.kubernetes.io/control-plane
          # Compute Nodes: 2 x [16 cores, 59Gi memory, 500Gi ephemeral-storage]
          # nominalQuota = count * size
          # borrowing / lending = size * 40%
          resources:
            - name: "cpu"
              nominalQuota:   32
              borrowingLimit: 12
              lendingLimit:   12
            - name: "memory"
              nominalQuota:   118Gi
              borrowingLimit: 47Gi
              lendingLimit:   47Gi
            - name: "ephemeral-storage"
              nominalQuota:   1000Gi
              borrowingLimit: 400Gi
              lendingLimit:   400Gi
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
