---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: skaha-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ skaha-workload, canfar-b-workload ]
  queueingStrategy: BestEffortFIFO
  cohort: skaha-cohort
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage"]
      flavors:
        - name: "default"
          resources:
            - name: "cpu"
              nominalQuota:   20 #30% of keel-dev
              borrowingLimit: 12
              lendingLimit:   12
            - name: "memory"
              nominalQuota:   52Gi #30% of keel-dev
              borrowingLimit: 32Gi
              lendingLimit:   32Gi
            - name: "ephemeral-storage"
              nominalQuota:   1088Gi #100% of keel-dev
              borrowingLimit: 200Gi
              lendingLimit:   100Gi
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
