---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: skaha-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ skaha-workload, canfar-b-workload ]
  queuingStrategy: BestEffortFifo
  cohort: skaha-cohort
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: standard
          resource:
            - name: "cpu"
              nominalQuota:   4 #TODO: 100% of the total cluster CPU
              borrowingLimit: 1 #TODO: 50% of the total cluster CPU
              lendingLimit:   1 #TODO: 50% of the total cluster CPU
            - name: "memory"
              nominalQuota:   4Gi #TODO: 100% of the total cluster memory
              borrowingLimit: 1Gi #TODO: 50% of the total cluster memory
              lendingLimit:   1Gi #TODO: 50% of the total cluster memory
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort: LowerPriority
    withClusterQueue: LowerPriority
  stopPolicy: None
---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: skaha-workload
  name: skaha-local-queue
spec:
  clusterQueue: skaha-cluster-queue
---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: canfar-b-workload
  name: canfar-b-local-queue
spec:
  clusterQueue: skaha-cluster-queue
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
