{{- if .Values.entryPoint }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ingress-route-tcp
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.entryPoint }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Release.Name }}-svc
      port: 2222
{{- else }}
# IngressRouteTCP is disabled because entryPoint is not configured.
# To enable it, set entryPoint to a valid Traefik entrypoint name.
{{- end }}
