{{- range $secretIndex, $secretName := .Values.secrets }}
{{/* Extra desired secrets, such as placing a self-signed CA Certificate. */}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretIndex }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range $certKey, $certValue := . }}
    {{ $certKey }}: {{ $certValue | quote }}
  {{- end }}
{{- end }}

{{/* The main secret file to contain configuration (and credentials) to authenticate with LDAP. */}}
---
apiVersion: v1
kind: Secret
metadata:
  name: sssd-config
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  sssd.conf: {{ tpl (.Files.Get "secret/sssd.conf") . | b64enc }}
