{{- if eq .Values.uwsDatabase.install true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-uws-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-uws-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Release.Name }}-uws-postgres
{{- end }}
