---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
spec:
  nodeLabels:
    skaha.opencadc.org/node-type: worker-node
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: skaha-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ skaha-workload, canfar-b-workload ]
  queueingStrategy: BestEffortFIFO
  cohort: skaha-cohort
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage", "nvidia.com/gpu"]
      flavors:
        - name: "default"
          # Cluster Hardware Configuration
          # Does not include
          #   - skaha.opencadc.org/node-type=service-node (p-nodes)
          #   - node-role.kubernetes.io/control-plane
          # Compute Nodes: 40 x [64 cores, 241Gi memory, 2048Gi ephemeral-storage]
          # GPU Nodes A: 3 x [8 cores, 40Gi memory, 140Gi ephemeral-storage, GRID-V100D-16C]
          # GPU Nodes B: 6 x [4 cores, 20Gi memory, 80Gi ephemeral-storage, GRID-V100D-8C]
          # nominalQuota = count * size - 2% overhead
          # borrowing / lending = size * 40%
          resources:
            - name: "cpu"
              nominalQuota:   2555
              borrowingLimit: 1022
              lendingLimit:   1022
            - name: "memory"
              nominalQuota:   9682Gi
              borrowingLimit: 3873Gi
              lendingLimit:   3873Gi
              # 40 nodes * 2048Gi = 81920Gi
            - name: "ephemeral-storage"
              nominalQuota:   81164Gi
              borrowingLimit: 32465Gi
              lendingLimit:   32465Gi
            - name: "nvidia.com/gpu"
              nominalQuota: 9
              borrowingLimit: 3
              lendingLimit: 3
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
