---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: skaha-workload
  name: skaha-local-queue
spec:
  clusterQueue: skaha-cluster-queue
---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: canfar-b-workload
  name: canfar-b-local-queue
spec:
  clusterQueue: skaha-cluster-queue
