{{- range $serviceName, $service := .Values.services }}
{{- if $service.serviceAccount.create -}}
{{$data := dict "serviceName" $serviceName "Values" $service "Chart" $.Chart "Release" $.Release }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "canfar.serviceAccountName" $data }}
  labels:
    {{- include "canfar.labels" $data | nindent 4 }}
  {{- with $service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $service.serviceAccount.automount }}
{{- end }}
{{- end }}