apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-ui-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "config/*").AsConfig . | indent 2 }}
{{- include "utils.extraConfig" (dict "extraConfigData" .Values.deployment.storageUI.extraConfigData) -}}
