# Example Local Queue configuration for Kueue.  This assumes the skaha-workload namespace exists, and the referenced ClusterQueue exists.
# This a single LocalQueue, but feel free to add as many as needed.
# @see https://kueue.sigs.k8s.io/docs/concepts/local_queue/
#
# jenkinsd 2025.09.11
#
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: skaha-workload
  name: canfar-science-platform-local-queue
spec:
  clusterQueue: canfar-science-platform-cluster-queue
