# Grant the service account from the Released and Workload namespaces access to the Kueue resources
#
# Workload Namespace RBAC
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: canfar-science-platform-kueue-role
  namespace: skaha-workload
rules:
- apiGroups:
  - "kueue.x-k8s.io"
  resources:
  - localqueues
  verbs:
  - get
  - list
  - status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canfar-science-platform-read-kueue
  namespace: skaha-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: canfar-science-platform-kueue-role
subjects:
- kind: ServiceAccount
  name: skaha
  namespace: skaha-system

#
# Released Namespace RBAC
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: canfar-science-platform-kueue-role
  namespace: skaha-system
rules:
- apiGroups:
  - "kueue.x-k8s.io"
  resources:
  - localqueues
  verbs:
  - get
  - list
  - status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canfar-science-platform-read-kueue
  namespace: skaha-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: canfar-science-platform-kueue-role
subjects:
- kind: ServiceAccount
  name: skaha
  namespace: skaha-system
