kubernetesClusterDomain: cluster.local

# Default values for skaha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# It's best to keep this set as such, unless you're willing to change these in several places.
skahaWorkload:
  namespace: skaha-workload
 
# Skaha web service deployment
deployment:
  hostname: myhost.example.com  # Change this!
  skaha:
    image: images.opencadc.org/platform/skaha:1.0.1
    imagePullPolicy: Always

    # Cron string for the image caching cron job schedule. Defaults to every half hour.
    imageCache:
      refreshSchedule: "*/30 * * * *"
  
    # Set the top-level-directory name that gets mounted at the root.
    # skahaTld: "/cavern"

    # Used when allocating first-time users into the system.
    defaultQuotaGB: "10"

    # Space delimited list of allowed Image Registry hosts.  These hosts should match the hosts in the User Session images.
    registryHosts: "images.canfar.net"

    init:
      # The image to use for the init container.  Unless you have a reason to change this, leave it alone.
      # This image is used to create the /home and /projects directories, in case Cavern is not already running.
      image: busybox:1.37.0
      imagePullPolicy: IfNotPresent

    # The IVOA GMS Group URI to verify users against for permission to use the Science Platform.
    # See https://www.ivoa.net/documents/GMS/20220222/REC-GMS-1.0.html#tth_sEc3.2
    # usersGroup: "ivo://example.org/gms?prototyping-groups/mini-src/platform-users"

    # The IVOA GMS Group URI to verify images without contacting Harbor.
    # See https://www.ivoa.net/documents/GMS/20220222/REC-GMS-1.0.html#tth_sEc3.2
    # adminsGroup: "ivo://example.org/gms?prototyping-groups/mini-src/platform-users"

    # Group URI for users to preempt headless jobs.
    # See https://www.ivoa.net/documents/GMS/20220222/REC-GMS-1.0.html#tth_sEc3.2
    # headlessGroup: "ivo://example.org/gms?prototyping-groups/mini-src/platform-users"

    # Group URI for users to ensure priority for their headless jobs.
    # See https://www.ivoa.net/documents/GMS/20220222/REC-GMS-1.0.html#tth_sEc3.2
    # headlessPriorityGroup: "ivo://example.org/gms?skaha-priority-headless-users"

    # Class name to set for priority headless jobs.
    # headlessPriorityClass: uber-user-preempt-high

    # Array of GMS Group URIs allowed to set the logging level.  If none set, then nobody can change the log level.
    # See https://www.ivoa.net/documents/GMS/20220222/REC-GMS-1.0.html#tth_sEc3.2 for GMS Group URIs
    # See https://github.com/opencadc/core/tree/main/cadc-log for Logging control
    # loggingGroups:
    #   - "ivo://example.org/gms?prototyping-groups/mini-src/platform-users"

    # The Resource ID (URI) of the Service that contains the Posix Mapping information
    # posixMapperResourceID: "ivo://example.org/posix-mapper"

    # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
    # oidcURI: https://iam.example.org/

    # The Resource ID (URI) of the GMS Service.
    # gmsID: ivo://example.org/gms

    # The absolute URL of the IVOA Registry where services are registered
    # registryURL: https://spsrc27.iaa.csic.es/reg

    # This applies to Skaha itself.  Meaning, this Pod will be scheduled as described
    # by the nodeAffinity clause.
    # Note the different indentation level compared to the sessions.nodeAffinity.
    # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/
    # nodeAffinity: {}

    # Settings for User Sessions.  Sensible defaults supplied, but can be overridden.
    # For units of storage, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory.
    sessions:
      expirySeconds: "345600"   # Duration, in seconds, until they expire and are shut down.
      maxCount: "3"  # Max number of sessions per user.
      minEphemeralStorage: "20Gi"   # The initial requested amount of ephemeral (local) storage.  Does NOT apply to Desktop sessions.
      maxEphemeralStorage: "200Gi"  # The maximum amount of ephemeral (local) storage to allow a Session to extend to.  Does NOT apply to Desktop sessions.

      persistentVolumeClaimName: "skaha-workload-cavern-pvc"  # The PVC that is mounted into User Sessions at /home and /projects.

      # The image pull policy for User Sessions (applies to ALL types).  This is the default, but can be overridden.  Deafults to Always.
      # @see https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
      # Example:
      #   imagePullPolicy: IfNotPresent
      imagePullPolicy: Always 

      # Optionally configure the initContainer image for Redis.  Useful for those not able to reach docker.io
      # Defaults to redis-7.4.2-alpine3.21.
      # Example:
      #   initContainerImage: "private-image-repo/project/my-own-redis:1.0"
      # initContainerImage:

      # Optionally configure the Kueue system to handle large workloads.  Configurable per session type (e.g. desktop, notebook, etc.).
      # Leaving this empty will default to submitting Jobs to the base Kubernetes system.
      # Provide a default configuration for all session types, or omit and only configure specific session types.
      # Provided PriorityClass names are "high", "medium", and "low".
      # @see https://kueue.sigs.k8s.io/docs/
      # @see https://github.com/opencadc/deployments/tree/main/configs/kueue
      # Example 1:
      #   # Configure notebook, desktop, and default session types.
      #   queue:
      #     notebook:
      #       queueName: "notebook-queue"
      #       priorityClass: "medium"
      #     desktop:
      #       queueName: "desktop-queue"
      #       priorityClass: "low"
      #     default:
      #       queueName: "default-queue"
      #       priorityClass: "medium"
      #
      # Example 2:
      #    # Configure contributed session types.  All else will use the bare Kubernetes system.
      #    queue:
      #      contributed:
      #        queueName: "contributed-queue"
      #        priorityClass: "high"
      #
      # Example 3:
      #    # Configure Kueue for all user session types.
      #    queue:
      #      default:
      #        queueName: "all-user-sessions-local-queue"
      #        priorityClass: "medium"
      queue: {}

      # This is a list of tolerations that will be added to the Pod spec of the User Sessions.
      # @see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      # @see ./README.md#notes-on-tolerations-and-nodeaffinity
      # 
      # Example:
      # tolerations:
      # - key: "key1"
      #   operator: "Equal"
      #   value: "value1"
      #   effect: "NoSchedule"
      # 
      tolerations: []

      # Optionally setup a separate host for User Sessions for Skaha to redirect to.  The HTTPS scheme is assumed.  Defaults to the Skaha hostname.
      # Example:
      #   hostname: myhost.example.org
      # hostname:

      # Optionally set the TLS configiuration that contains the certificate information for the alternate hostname for User Sessions.  This will go into the Traefik IngressRoute spec.
      # @see https://doc.traefik.io/traefik/v2.3/routing/providers/kubernetes-crd/#kind-ingressroute
      # Example:
      #   tls:
      #     secretName: myhost-tls-secret
      tls: {}

      # Declare extra volume mounts in User Sessions.  The "type: parameter in volume section is constant.
      # extraVolumes:
      # - name: example-pvc-name
      #   volume:
      #     type: PVC           # PVC is for Persistant volume claim
      #     name: pvc-name
      #   volumeMount:
      #     mountPath: "/pvc-volume-mount"
      #     subPath: "pvc"
      # - name: example-hostpath-name
      #   volume:
      #     type: HOST_PATH     # HOST_PATH is for host path
      #     hostPath: "/host-path"
      #     hostPathType: Directory
      #   volumeMount:
      #     mountPath: "/host-path"
      #     readOnly: true
      #     mountPropagation: HostToContainer
      # - name: config-map-volume
      #   volume:
      #     type: CONFIG_MAP    # CONFIG_MAP is for config map
      #     name: example-config-map-name
      #     defaultMode: "0777"
      #   volumeMount:
      #     mountPath: "/cmp"
      # - name: secret-volume
      #   volume:
      #     type: SECRET        # SECRET is for secrets
      #     name: example-secret-name
      #     defaultMode: "0777"
      #   volumeMount:
      #     mountPath: "/scrt"

      # When set to 'true' this flag will enable GPU node scheduling.  Don't forget to declare any related GPU configurations, if appropriate, in the nodeAffinity below!
      # gpuEnabled: false

      # Set the YAML that will go into the "affinity.nodeAffinity" stanza for Pod Spec in User Sessions.  This can be used to enable GPU scheduling, for example, 
      # or to control how and where User Session Pods are scheduled.  This can be potentially dangerous unless you know what you are doing.
      # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity
      # nodeAffinity: {}

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Resources provided to the Skaha service.
    # For units of storage, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory.
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # If the base names have changed, then change them here, otherwise leave them.
    priorityClassName: uber-user-preempt-high
    serviceAccountName: skaha

    # The IdentityManager class handling authentication.  This should generally be left alone
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: skaha-cacert-secret

    # API version that is currently in use for this deployment.  Leave this alone unless you know what you're doing.
    # This the version that will show up in the path for the request (e.g. '/skaha/v0/session').
    # Example:
    #   apiVersion: 'v0'
    apiVersion: 'v1'

  # Specify extra hostnames that will be added to the Pod's /etc/hosts file.  Note that this is in the
  # deployment object, not the skaha one.
  # extraHosts:
  #   - ip: 127.3.34.5
  #     hostname: myhost.example.org
  # extraHosts: []

# This is a list of tolerations that will be added to the Pod spec of the Skaha API.
# @see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
# @see ./README.md#notes-on-tolerations-and-nodeaffinity
# 
# Example:
# tolerations:
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
# 
tolerations: []

# Port to expose from the service.  This will ultimately serve port 8080 (default Tomcat port), but will
# be exposed as per the port below.  Useful for running multiple deployments side-by-side.
# Defaults to 8080.
# Example:
#   service:
#     port: 8081. # To map port 8081 to port 8080.
service:
  port: 8080

# Selectively disable ingress if desired.  This is enabled by default.
ingress:
  enabled: true
  path: /skaha

secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # skaha-cacert-secret:
  #   ca.crt: <base64 encoded CA crt>

# Set these appropriately to match your Persistent Volume labels.
storage:
  service:
    spec:
      # YAML for service mounted storage.
      # Example is the persistentVolumeClaim below.
      # persistentVolumeClaim:
      #   claimName: skaha-pvc\

# For caching images from the Image Repository and for the writing the POSIX Users and Groups to be shared with Job files
redis:
  architecture: 'standalone'
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]

# Kueue configuration.  This will not install Kueue by default, due to its complexity many deployers may wish to install their own.
kueue:
  install: false
  
  # Set this here to ensure the created secret for the webhook certificates has a predictable name, rather than the Release.Name from the parent Chart (skaha).
  fullnameOverride: "kueue"

  # Enable prometheus metrics for the kueue controller.
  enablePrometheus: true

  enableCertManager: false

  clusterQueueResources:
    - name: "cpu"
      nominalQuota:   "1680"
      borrowingLimit: "420"
      lendingLimit:   "420"
    - name: "memory"
      nominalQuota:   "6562Gi"
      borrowingLimit: "1640Gi"
      lendingLimit:   "1640Gi"
      # 40 nodes * 2048Gi = 81920Gi
    - name: "ephemeral-storage"
      nominalQuota:   "52636Gi"
      borrowingLimit: "13159Gi"
      lendingLimit:   "13159Gi"
    - name: "nvidia.com/gpu"
      nominalQuota: "18"
      borrowingLimit: "0"
      lendingLimit: "0"

  # Kueue Controller Configuration
  controllerManager:
    # Kueue Feature Gates, deprecated features excluded
    # Based on v0.10.0 retrieved on 2025-01-01
    # Source: https://kueue.sigs.k8s.io/docs/installation/
    featureGates:
      - name: LocalQueueMetrics
        enabled: true
    # Kueue Deployment Configuration
    manager:
      resources:
        limits:
          cpu: "2"
          memory: 1536Mi
        requests:
          cpu: "1"
          memory: 512Mi

  # controller_manager_config.yaml. controllerManager utilizes this yaml via manager-config Configmap.
  managerConfig:
    controllerManagerConfigYaml: |-
      apiVersion: config.kueue.x-k8s.io/v1beta1
      kind: Configuration

      health:
        healthProbeBindAddress: :8081

      metrics:
        # Bind to for serving prometheus metrics, set to 0 to disable
        # Maps to metricsService.ClusterIP
        bindAddress: :8443
        # Report the cluster queue resource usage and quotas metrics
        enableClusterQueueResources: true

      webhook:
        port: 9443

      leaderElection:
        leaderElect: true
        resourceName: c1f6bfd2.kueue.x-k8s.io

      controller:
        # Number of concurrent reconciliation allowed for a controller.
        groupKindConcurrency:
          Job.batch: 256
          Pod: 4
          Workload.kueue.x-k8s.io: 256
          LocalQueue.kueue.x-k8s.io: 256
          ClusterQueue.kueue.x-k8s.io: 256
          ResourceFlavor.kueue.x-k8s.io: 4

      # Client connection details for the k8s_apiserver
      clientConnection:
        # queries/second allowed for k8s_apiserver
        qps: 64
        # extra queries to accumulate when a client is exceeding its rate.
        burst: 128

      # Controls whether or not Kueue reconciles jobs that don't set the annotation kueue.x-k8s.io/queue-name.
      # If set to true, then those jobs will be suspended and never started unless they are assigned a queue
      # and eventually admitted. This also applies to jobs created before starting the kueue controller.
      # Defaults to false; therefore, those jobs are not managed and if they are created unsuspended,
      # they will start immediately.
      manageJobsWithoutQueueName: false

      managedJobsNamespaceSelector:
        matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - skaha-workload

      integrations:
        # List of framewor to be integrated with Kueue.
        frameworks:
        - "batch/job"
        labelKeysToCopy:
        - canfar-net-sessionID
        - canfar-net-appID
        - canfar-net-sessionName
        - canfar-net-sessionType
        - canfar-net-userid
        - batch.kubernetes.io/job-name
