---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
    cadc-log.properties: |
{{- range $val := .Values.loggingGroups }}
        group = {{ $val }}
{{- end }}
    cadc-registry.properties: |
        ivo://ivoa.net/std/GMS#search-1.0 = {{ .Values.gmsID | required "The GMS locator (gmsID) is required" }}
        ivo://ivoa.net/std/GMS#users-1.0 = {{ .Values.gmsID }}
        ivo://ivoa.net/std/UMS#users-1.0 = {{ .Values.gmsID }}
        ivo://ivoa.net/sso#OAuth = {{ .Values.oidcURI }}
        ivo://ivoa.net/sso#OpenID = {{ .Values.oidcURI }}

        http://www.opencadc.org/std/posix#group-mapping-0.1 = {{ .Values.resourceID | required "The locator for the POSIX Mapper service (resourceID) is required" }}
        http://www.opencadc.org/std/posix#user-mapping-0.1 = {{ .Values.resourceID }}

        ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ .Values.registryURL | required "A registryURL is required" }}

    catalina.properties: |
        tomcat.connector.scheme=https
        tomcat.connector.proxyName={{ .Values.hostname }}
        tomcat.connector.proxyPort=443
        ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
        ca.nrc.cadc.util.Log4jInit.messageOnly=true
        ca.nrc.cadc.auth.IdentityManager={{ .Values.identityManagerClass }}

        # database connection pools
        {{- $postgresql := required "Missing PostgreSQL configuration at .Values.postgresql" .Values.postgresql }}
        {{- with $postgresql }}
        org.opencadc.posix.mapper.maxActive={{ .maxActive | default 8 }}
        org.opencadc.posix.mapper.url={{ .url | required "Missing PostgreSQL URL at .Values.postgresql.url" }}

        {{- $postgresqlAuth := required "Missing PostgreSQL authentication configuration at .Values.postgresql.auth" .auth }}
        org.opencadc.posix.mapper.username={{ $postgresqlAuth.username | required "Missing PostgreSQL username at .Values.postgresql.auth.username" }}
        org.opencadc.posix.mapper.password={{ $postgresqlAuth.password | required "Missing PostgreSQL password at .Values.postgresql.auth.password" }}
        {{- end }}

    posix-mapper.properties: |
        # service identity
        org.opencadc.posix.mapper.resourceID={{ .Values.resourceID }}

        # database schema
        org.opencadc.posix.mapper.schema={{ .Values.postgresql.schema }}

        # ID ranges to allow some customization where administration is necessary
        org.opencadc.posix.mapper.uid.start={{ .Values.minUID }}
        org.opencadc.posix.mapper.gid.start={{ .Values.minGID }}
    war-rename.conf: |
        {{- if .Values.applicationName }}
        mv posix-mapper.war {{ .Values.applicationName }}.war
        {{- end }}

