apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-add-user-config
  namespace: {{ .Release.Namespace }}
binaryData:
  casa-config.tar:
    {{ .Files.Get "add-user-config/casa/casa-config.tar" | b64enc | nindent 4 }}
data:
  {{- (.Files.Glob "add-user-config/*").AsConfig | nindent 2 }}
