apiVersion: v1
kind: ConfigMap
metadata:
  name: add-user-config
  namespace: {{ .Values.skaha.namespace }}
binaryData:
  desktop-config.tar:
    {{ .Files.Get "add-user-config/desktop-config.tar" | b64enc | nindent 4 }}
