apiVersion: v1
kind: ConfigMap
metadata:
  name: init-users-datasets-symlink-config
  namespace: {{ .Values.skahaWorkload.namespace }}
data:
  {{- (.Files.Glob "init-users-datasets-symlink-config/*").AsConfig | nindent 2 }}
