apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-launch-scripts
  namespace: {{ .Values.skahaWorkload.namespace }}
data:
  {{- (.Files.Glob "launch-scripts/*").AsConfig | nindent 2 }}
