{{- with .Values.experimentalFeatures }}
{{- if eq .enabled true }}
{{- with .sessionLimitRange }}
{{- if eq .enabled true }}
---
apiVersion: v1
kind: LimitRange
metadata:
    name: {{ $.Release.Name }}-session-limit-range
    namespace: {{ $.Values.skahaWorkload.namespace }}
spec:
{{- with .limitSpec }}
  limits:
    - type: Container
{{ . | toYaml | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
