# Common middleware logic for Firefly sessions.  Exists here to only create it once and share it amongst the Firefly User Sessions.
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: firefly-set-x-forwarded-proto
  namespace: {{ .Values.skahaWorkload.namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
