apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-skaha-tomcat-svc
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ .Release.Name }}-skaha-tomcat-svc
spec:
  ports:
  - port: {{ .Values.service.port | default "8080" }}
    targetPort: 8080
    name: http-connection
    protocol: TCP
  selector:
    run: {{ .Release.Name }}-skaha-tomcat
