---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.skaha.namespace }}
{{- with .Values.skahaWorkload }}
{{- if and .namespace (not (eq $.Values.skaha.namespace .namespace)) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
{{- end }}
{{- end }}
