name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual documentation deployment'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: ${{ github.repository == 'opencadc/deployments' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
