name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Helm tool installer
        uses: Azure/setup-helm@v4.3.1

      - name: Helm Dependency Updates
        run: |
          for chart in helm/applications/*/; do helm dependency update "$chart" 2>/dev/null || true; done

      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: 'stable'

      - name: Install Helm Docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          python-version: 3.13
          enable-cache: "auto"
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
          restore-cache: "true"
          save-cache: "true"

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Run pre-commit checks
        id: precommit
        continue-on-error: true
        run: uv run pre-commit run -a

      - name: Share pre-commit guidance
        if: ${{ github.event_name == 'pull_request' && (steps.precommit.outcome == 'failure') }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### ⚠️ Pre-commit Checks Failed

            ${{ steps.precommit.outcome == 'failure' && '- Run `uv run pre-commit run -a` locally to reproduce the issues.' || '' }}

            To reproduce the issues locally, run the following commands:

            ```bash
            git clone ${{ github.event.pull_request.head.repo.clone_url }}
            git checkout -b ${{ github.event.pull_request.head.ref  }}
            uv run pre-commit run -a
            ```

            To always run pre-commit checks locally before pushing changes, simple run the following command once:

            ```bash
            uv run pre-commit install
            ```

            #### Resources
            - [Documentation to install `uv`](https://docs.astral.sh/uv/getting-started/installation/)
            - [Conventional Commits](https://www.conventionalcommits.org/) standards for writing commit messages
            - [Commitizen](https://commitizen-tools.github.io/commitizen/) CLI tool for writing commit messages
            - [pre-commit](https://pre-commit.com/) CLI tool for running pre-commit hooks

      - name: Celebrate spotless PR
        if: ${{ github.event_name == 'pull_request' && steps.precommit.outcome == 'success' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### ✅ All pre-commit checks passed

            Thanks for keeping the repo tidy! ✨

      - name: Fail if checks failed
        if: ${{ steps.precommit.outcome == 'failure' }}
        run: |
          git diff --exit-code

      - name: Cleanup pre-commit cache
        run: |
          uv run pre-commit gc
