name: Renovate

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual renovate run'
        required: true
        type: string

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('.github/workflows/renovate.yml') }}

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v43.0.18
        with:
          configurationFile: renovate.json
          renovate-version: 41.157.0
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
